// 业务场景下拉选择项
export const businessScenarioDict = {
    type: [{
        label: '控制器',
        value: '0'
    }, {
        label: '联合控制员',
        value: '1'
    }, {
        label: '加工机',
        value: '2'
    }],
    dataSubjectsRegion: [{
        label: '非洲',
        value: '0'
    }, {
        label: '南极洲',
        value: '1'
    }, {
        label: '亚太地区',
        value: '2'
    }, {
        label: '加利福尼亚',
        value: '3'
    }, {
        label: '加拿大',
        value: '4'
    }, {
        label: '中美洲/加勒比/墨西哥',
        value: '5'
    }, {
        label: '欧洲（EEA）',
        value: '6'
    }, {
        label: '欧洲（非欧洲经济区）',
        value: '7'
    }, {
        label: '欧洲（联合王国）',
        value: '8'
    }, {
        label: '中东',
        value: '9'
    }, {
        label: '南美洲',
        value: '10'
    }, {
        label: '美国',
        value: '11'
    }], 
    purposeOfProcessing: [{
        label: '背景调查',
        value: '0'
    }, {
        label: '利益',
        value: '1'
    }, {
        label: '校园招聘',
        value: '2'
    }, {
        label: '补偿',
        value: '3'
    }, {
        label: '消费者参与度',
        value: '4'
    }, {
        label: '合同义务',
        value: '5'
    }, {
        label: '客户关系管理',
        value: '6'
    }, {
        label: '客户服务',
        value: '7'
    }, {
        label: '直接营销',
        value: '8'
    }, {
        label: '电子商务活动',
        value: '9'
    }, {
        label: '资金',
        value: '10'
    }, {
        label: '历史研究',
        value: '11'
    }, {
        label: '保险处理',
        value: '12'
    }, {
        label: '领导资格',
        value: '13'
    }, {
        label: '市场调查',
        value: '14'
    }, {
        label: '新产品开发',
        value: '15'
    }, {
        label: '在线学习倡议',
        value: '16'
    }, {
        label: '网上招聘活动',
        value: '17'
    }, {
        label: '工资单处理',
        value: '18'
    }, {
        label: '公共卫生和安全',
        value: '19'
    }, {
        label: '退休计划',
        value: '20'
    }, {
        label: '销售额',
        value: '21'
    }, {
        label: '科学研究',
        value: '22'
    }, {
        label: '旅行计划',
        value: '23'
    }], 
    dataSource: [{
        label: '资产或供应商',
        value: '0'
    }, {
        label: '直接来自个人',
        value: '1'
    }],
    transferMethodFromSources: [{
        label: "API's",
        value: '0'
    }, {
        label: '应用集成',
        value: '1'
    }, {
        label: '电子版',
        value: '2'
    }, {
        label: '电子邮件',
        value: '3'
    }, {
        label: '文件传输',
        value: '4'
    }, {
        label: '纸张格式',
        value: '5'
    }, {
        label: 'Web表单',
        value: '6'
    }],
    destinations: [{
        label: "资产或供应商",
        value: '0'
    }, {
        label: '直接针对个人',
        value: '1'
    }],
    transferMethodToDestinations: [{
        label: "API's",
        value: '0'
    }, {
        label: '应用集成',
        value: '1'
    }, {
        label: '电子版',
        value: '2'
    }, {
        label: '电子邮件',
        value: '3'
    }, {
        label: '文件传输',
        value: '4'
    }, {
        label: '纸张格式',
        value: '5'
    }, {
        label: 'Web表单',
        value: '6'
    }],
    partiesWhoAccessUseData: [{
        label: 'B2B客户',
        value: '0'
    }, {
        label: '商业伙伴',
        value: '1'
    }, {
        label: '客户服务代表',
        value: '2'
    }, {
        label: '执行董事/董事会',
        value: '3'
    }, {
        label: '外部机构',
        value: '4'
    }, {
        label: '外部审计师',
        value: '5'
    }, {
        label: '财务/会计团队',
        value: '6'
    }, {
        label: '内部审计师',
        value: '7'
    }, {
        label: '基于需要了解的内部员工',
        value: '8'
    }, {
        label: '法律团队',
        value: '9'
    }, {
        label: '操作/维护团队',
        value: '10'
    }, {
        label: '公共当局/政府机构',
        value: '11'
    }, {
        label: '销售/营销团队',
        value: '12'
    }, {
        label: '服务提供商',
        value: '13'
    }, {
        label: '工会/工作委员会',
        value: '14'
    }, {
        label: '新产品开发',
        value: '15'
    }, {
        label: '在线学习倡议',
        value: '16'
    }],
    locationsOfPartiesAccessUse: [{
        label: '未知的',
        value: '0'
    }, {
        label: '阿富汗',
        value: '1'
    }, {
        label: '阿兰群岛',
        value: '2'
    }, {
        label: '阿尔巴尼亚',
        value: '3'
    }, {
        label: '阿尔及利亚',
        value: '4'
    }, {
        label: '美属萨摩亚',
        value: '5'
    }, {
        label: '安道尔',
        value: '6'
    }, {
        label: '安哥拉',
        value: '7'
    }, {
        label: '安圭拉',
        value: '8'
    }, {
        label: '南极洲',
        value: '9'
    }, {
        label: '安提瓜和巴布达',
        value: '10'
    }, {
        label: '阿根廷',
        value: '11'
    }, {
        label: '亚美尼亚',
        value: '12'
    }, {
        label: '阿鲁巴',
        value: '13'
    }, {
        label: '澳大利亚',
        value: '14'
    }, {
        label: '奥地利',
        value: '15'
    }, {
        label: '巴哈马群岛',
        value: '16'
    }, {
        label: '巴林',
        value: '17'
    }, {
        label: '孟加拉国',
        value: '18'
    }, {
        label: '巴巴多斯',
        value: '19'
    }, {
        label: '白俄罗斯',
        value: '20'
    }, {
        label: '比利时',
        value: '21'
    }, {
        label: '伯利兹',
        value: '22'
    }, {
        label: '贝宁',
        value: '23'
    }, {
        label: '百慕大群岛',
        value: '24'
    }, {
        label: '不丹',
        value: '25'
    }, {
        label: '玻利维亚',
        value: '26'
    }, {
        label: '博内尔',
        value: '27'
    }, {
        label: '波斯尼亚和黑塞哥维那',
        value: '28'
    }, {
        label: '博茨瓦纳',
        value: '29'
    }, {
        label: '布韦特岛',
        value: '30'
    }, {
        label: '巴西',
        value: '31'
    }, {
        label: '英属印度洋领土',
        value: '32'
    }, {
        label: '英属维尔京群岛',
        value: '33'
    }, {
        label: '文莱',
        value: '34'
    }, {
        label: '保加利亚',
        value: '35'
    }, {
        label: '布基纳法索',
        value: '36'
    }, {
        label: '布隆迪',
        value: '37'
    }, {
        label: '柬埔寨',
        value: '38'
    }, {
        label: '喀麦隆',
        value: '39'
    }, {
        label: '加拿大',
        value: '40'
    }, {
        label: '佛得角',
        value: '41'
    }, {
        label: '荷兰加勒比区',
        value: '42'
    }, {
        label: '开曼群岛',
        value: '43'
    }, {
        label: '中非共和国',
        value: '44'
    }, {
        label: '查德',
        value: '45'
    }, {
        label: '智利',
        value: '46'
    }, {
        label: '中国',
        value: '47'
    }],
    legalBasisForProcessing: [{
        label: '个人同意',
        value: '0'
    }, {
        label: '遵守法律义务是必要的',
        value: '1'
    }, {
        label: '履行与个人的合同是必要的',
        value: '2'
    }, {
        label: '这对于执行为公众利益而执行的任务是必要的',
        value: '3'
    }, {
        label: '为了我们（组织）的合法利益，这是必要的',
        value: '4'
    }, {
        label: '为了保护个人的切身利益，这是必要的',
        value: '5'
    }],
    crossBorderTransferMechanism: [{
        label: '充分性决策',
        value: '0'
    }, {
        label: '认可的核证机制',
        value: '1'
    }, {
        label: '认可的行为准则',
        value: '2'
    }, {
        label: '主管监管机构的授权',
        value: '3'
    }, {
        label: '具有约束力的公司规则',
        value: '4'
    }, {
        label: '欧盟-美国隐私保护组织',
        value: '5'
    }, {
        label: '数据主体的明确同意',
        value: '6'
    }, {
        label: '公共当局或机构之间具有法律约束力且可执行的文书',
        value: '7'
    }, {
        label: '标准数据保护条款',
        value: '8'
    }, {
        label: 'GDPR第49（1）条第二款规定的适当保障措施',
        value: '9'
    }, {
        label: '根据欧盟或成员国法律，从公共登记处进行转让',
        value: '10'
    }, {
        label: '出于公共利益的重要原因，转让是必要的',
        value: '11'
    }, {
        label: '为了数据主体的利益，转让是履行合同所必需的',
        value: '12'
    }, {
        label: '传输是履行与数据主体的合同所必需的',
        value: '13'
    }, {
        label: '为确立、行使或辩护法律主张，转让是必要的',
        value: '14'
    }, {
        label: '为了保护数据主体或其他人的切身利益，传输是必要的',
        value: '15'
    }],
    businessFunction: [{
        label: '资金',
        value: '0'
    }, {
        label: '政府关系/公共政策',
        value: '1'
    }, {
        label: '人力资源/道德',
        value: '2'
    }, {
        label: 'IT/安全',
        value: '3'
    }, {
        label: '内部审计/风险管理',
        value: '4'
    }, {
        label: '法律/合同',
        value: '5'
    }, {
        label: '营销/业务发展',
        value: '6'
    }, {
        label: '操作',
        value: '7'
    }, {
        label: '销售额',
        value: '8'
    }],
    legitimateInterest: [{
        label: '直接营销目的',
        value: '0'
    }, {
        label: '确保网络和信息安全',
        value: '1'
    }, {
        label: '防止欺诈',
        value: '2'
    }, {
        label: '防止未经授权访问电子通信网络',
        value: '3'
    }, {
        label: '处理付款或订阅以履行财务承诺或合同',
        value: '4'
    }, {
        label: '向主管当局报告可能的犯罪行为或对公共安全的威胁',
        value: '5'
    }, {
        label: '出于内部管理目的在公司集团内共享客户数据',
        value: '6'
    }, {
        label: '出于内部管理目的在公司集团内共享员工数据',
        value: '7'
    }, {
        label: '阻止对计算机和电子通信系统的破坏',
        value: '8'
    }],
    scheduleConditionForProcessing: [{
        label: '归档、研究和统计',
        value: '0'
    }, {
        label: '就业、社会保障和社会保护法',
        value: '1'
    }, {
        label: '明确同意',
        value: '2'
    }, {
        label: '健康或社会护理',
        value: '3'
    }, {
        label: '法律主张和司法行为',
        value: '4'
    }, {
        label: '数据主体公布',
        value: '5'
    }, {
        label: '非营利组织',
        value: '6'
    }, {
        label: '公共卫生',
        value: '7'
    }, {
        label: '实质性公共利益条件',
        value: '8'
    }, {
        label: '切身利益',
        value: '9'
    }],
}